spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # mybatis 로그
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/spring?characterEncoding=utf8
    username: root
    password: m2makstp
    mapper-locations: classpath:/mapper/**/*.xml

jwt:
  secret: jwtSecretKey
  expire: 86400000

logging:
  level:
#    com:
#      zaxxer:
#        hikari: INFO
#    javax:
#      sql:
#        DataSource: OFF
    jdbc:
      audit: OFF # JDBC 트러블슈팅 경우를 제외하고는 사용 권장 X
      resultset: OFF # ResultSet을 포함한 모든 JDBC 호출 정보를 출력
      resultsettable: DEBUG  #SQL 결과 데이터 Table형식으로 출력
      sqlonly: OFF     #SQL만 로그만 출력
      sqltiming: DEBUG    #SQL + 소요시간 출력
      connection : OFF  # 커넥션 연결/종료 정보 출력